Repository shellscape/webpack-plugin-serve, pull requests merged in 2018-12, with the labels that each got.

#40 feat: Node v8 support via socket upgrade handler
  lib/server.js
Labels: pr³ 🔧 feature, s² 🔥🔥 important, x³ ⋅ hold

#44 feat: client websocket connection retry
  README.md
  client.js
  lib/client/ClientSocket.js
  lib/client/client.js
  lib/client/hmr.js
  lib/client/log.js
  lib/client/overlays/progress-minimal.js
  lib/client/overlays/progress.js
  lib/client/overlays/status.js
  lib/client/overlays/util.js
  lib/index.js
  test/fixtures/simple/webpack.config.js
  test/snapshots/plugin.test.js.md
  test/snapshots/plugin.test.js.snap
Labels: pr³ 🔧 feature, v⁴ ⋅ minor

#56 fix: html-webpack-plugin child compiler chunk id
  lib/hmr-plugin.js
  package-lock.json
  package.json
Labels: pr⁴ 🔧 fix, s¹ 🔥🔥🔥 critical

#61 fix: add close passthrough method to ClientSocket #59
  lib/client/ClientSocket.js
Labels: pr⁴ 🔧 fix, s² 🔥🔥 important

#63 fix: use static hmr filenames
  lib/errors.js
  lib/hmr-plugin.js
  test/fixtures/simple/index.html
Labels: pr⁴ 🔧 fix, v⁴ ⋅ minor

#69 fix: test: fixes host and port Promise support. adds integration tests.
  .circleci/config.yml
  .circleci/setup-puppeteer.sh
  lib/index.js
  lib/server.js
  lib/validate.js
  package-lock.json
  package.json
  test/fixtures/multi/component.js
  test/fixtures/multi/webpack.config.js
  test/fixtures/multi/work.js
  test/fixtures/proxy/proxy-rewrite.config.js
  test/fixtures/proxy/webpack.config.js
  test/fixtures/simple/component.js
  test/fixtures/simple/webpack.config.js
  test/helpers/puppeteer.js
  test/integration/multi-hmr.test.js
  test/integration/single-hmr.test.js
  test/proxy-rewrite.test.js
  test/proxy.test.js
  test/snapshots/plugin.test.js.md
  test/snapshots/plugin.test.js.snap
  test/snapshots/proxy.test.js.snap
Labels: pr⁴ 🔧 fix, pr⁸ 🔧 test, s¹ 🔥🔥🔥 critical

#71 docs: add custom open uri recipe
  recipes/open-custom-uri.md
Labels: pr² 🔧 docs, s³ 🔥 nice to have

#70 fix: position status overlay absolute. fixes #67
  lib/client/overlays/status.js
  test/fixtures/multi/index.html
  test/fixtures/simple/index.html
Labels: pr⁴ 🔧 fix, s² 🔥🔥 important

#76 fix: promise, null validation. use joi.bind
  lib/validate.js
  package-lock.json
  package.json
  test/snapshots/validate.test.js.md
  test/snapshots/validate.test.js.snap
  test/validate.test.js
Labels: pr⁴ 🔧 fix, pr⁸ 🔧 test, s¹ 🔥🔥🔥 critical

#75 docs: add size badges to FEATURES.md
  .github/FEATURES.md
Labels: pr² 🔧 docs, s³ 🔥 nice to have
