Repository shellscape/webpack-plugin-serve, pull requests merged in 2019-01, with the labels that each got.

#82 fix: z-index on overlays set to max allowed. fix #81
  lib/client/overlays/progress-minimal.js
  lib/client/overlays/progress.js
  lib/client/overlays/status.js
Labels: pr⁴ 🔧 fix, s² 🔥🔥 important

#83 feat: static middleware options
  README.md
  index.d.ts
  lib/middleware.js
Labels: pr³ 🔧 feature, s³ 🔥 nice to have, v⁴ ⋅ minor

#97 feat: add client.silent option
  README.md
  client.js
  lib/client/client.js
  lib/client/log.js
Labels: pr³ 🔧 feature

#98 fix: strip accept header when using history-api-fallback
  README.md
  lib/middleware.js
Labels: pr⁴ 🔧 fix
